// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} base64Str
 * @returns {$CancellablePromise<void>}
 */
export function CommitRecord(base64Str) {
    return $Call.ByID(1889488809, base64Str);
}

/**
 * @param {$models.App | null} app
 * @returns {$CancellablePromise<void>}
 */
export function Init(app) {
    return $Call.ByID(1184374307, app);
}

/**
 * @param {$models.InitRequestData | null} initData
 * @returns {$CancellablePromise<$models.Result | null>}
 */
export function InitConn(initData) {
    return $Call.ByID(2248557669, initData).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function OnShutdown() {
    return $Call.ByID(2383980714);
}

/**
 * @param {$models.LiveConfig} configData
 * @returns {$CancellablePromise<$models.Result | null>}
 */
export function SetConfig(configData) {
    return $Call.ByID(2392563281, configData).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} windowID
 * @returns {$CancellablePromise<void>}
 */
export function ShowWindow(windowID) {
    return $Call.ByID(3242331696, windowID);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function StopConn() {
    return $Call.ByID(3932225391);
}

// Private type creation functions
const $$createType0 = $models.Result.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
