// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {$models.InitRequestData | null} initData
 * @returns {Promise<$models.Result | null> & { cancel(): void }}
 */
export function InitConn(initData) {
    let $resultPromise = /** @type {any} */($Call.ByID(2248557669, initData));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType1($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * @param {$models.LiveConfig} configData
 * @returns {Promise<$models.Result | null> & { cancel(): void }}
 */
export function SetConfig(configData) {
    let $resultPromise = /** @type {any} */($Call.ByID(2392563281, configData));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType1($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * @param {string} windowID
 * @returns {Promise<void> & { cancel(): void }}
 */
export function ShowWindow(windowID) {
    let $resultPromise = /** @type {any} */($Call.ByID(3242331696, windowID));
    return $resultPromise;
}

/**
 * @returns {Promise<void> & { cancel(): void }}
 */
export function StopConn() {
    let $resultPromise = /** @type {any} */($Call.ByID(3932225391));
    return $resultPromise;
}

// Private type creation functions
const $$createType0 = $models.Result.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
