// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function InitConn(arg1) {
  return window['go']['main']['App']['InitConn'](arg1);
}

export function SetConfig(arg1) {
  return window['go']['main']['App']['SetConfig'](arg1);
}

export function StopConn() {
  return window['go']['main']['App']['StopConn']();
}
