// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function InitConn(arg1:main.InitRequestData):Promise<main.Result>;

export function SetConfig(arg1:main.LiveConfig):Promise<main.Result>;

export function StopConn():Promise<void>;
